# Generated by Django 3.2.9 on 2021-12-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0002_auto_20211124_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.contributors'),
        ),
    ]
