# Generated by Django 3.2.9 on 2021-12-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SoftDesk', '0003_alter_comments_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.contributors'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='issue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.issues'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.projects'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='assignee_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.contributors'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='author_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SoftDesk.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
